fix generation bug

diff --git a/go/scripts-gen b/go/scripts-gen
--- a/go/scripts-gen
+++ b/go/scripts-gen
@@ -1,48 +1,44 @@
 #!/bin/bash
 
-
-for i in "stable" "beta" "nightly"
-do
+for i in "stable" "beta" "nightly"; do
     echo "generating ${i} script..."
-    echo -e "#!/bin/bash\n" > "${i}"
-    echo "PROVIDER=github.com" >> "${i}"
-    echo "PROVIDER_USERNAME=" >> "${i}"
-    echo "REPOSITORY=" >> "${i}"
-    echo "URI=\"https://\${PROVIDER}/\${PROVIDER_USERNAME}/\${REPOSITORY}\"" >> "${i}"
-    echo "REQUIRED=('git')" >> "${i}"
-    echo "COMMANDS=('go:run')" >> "${i}"
-    echo "CHANNEL=${i}" >> "${i}"
-    echo "TIME=10" >> "${i}"
-    echo "INSTALLER=apt-get" >> "${i}"
-    echo -e "INSTALL_OPTIONS=install\n" >> "${i}"
-    echo "for x in \${REQUIRED}"  >> "${i}"
-    echo "do"  >> "${i}"
-    echo -e "\t\${INSTALLER} \${INSTALL_OPTIONS} \"\${x}\"" >> "${i}"
-    echo -e "done\n" >> "${i}"
-    echo "STR=\$(realpath . )" >> ${i}
-    echo "SUB='go'" >> "${i}"
-    echo -e "\nif [[ \"\$STR\" == *\"\$SUB\"* ]]" >> "${i}"
-    echo "then" >> "${i}"
-    echo -e "\techo \"\${CHANNEL}\"" >> "${i}"
-    echo -e "fi\n" >> "${i}"      
-    echo "git clone \"\${URI}\" continuous && cd continuous || exit 1" >> "${i}"
-    echo "git log -1  && sleep \"\${TIME}\" || exit 1" >> "${i}"
-    echo -e "for x in \${COMMANDS}"  >> "${i}"
-    echo "do"  >> "${i}"
-    echo -e "\tprogram=\$(echo \"\${x}\" | cut -f1 -d :)" >> "${i}"
-    echo -e "\targ=\$(echo \"\${x}\" | cut -f2 -d :)" >> "${i}"
-    echo -e "\tfilenames=\$(ls ./*.go)" >> "${i}"
-    echo -e "\n\tfor x in \${filenames}" >> "${i}"
-    echo -e "\tdo" >> "${i}"
-    echo -e "\t\t\${program} \${arg} \"\${x}\"" >> "${i}"
-    echo -e "\t\tif [ \"\$?\" != 0 ]" >> "${i}"
-    echo -e "\t\tthen" >> "${i}"
-    echo -e "\t\t\texit 1" >> "${i}"
-    echo -e "\t\tfi" >> "${i}"
-    echo -e "\tdone" >> "${i}"
-    echo -e "done\n" >> "${i}"
-    echo "cd .." >> "${i}"
-    echo "rm -rf continuous" >> "${i}"
-    chmod +x "${i}"
-done
+    {
+        echo -e "#!/bin/bash\n"
+        echo "PROVIDER=github.com"
+        echo "PROVIDER_USERNAME="
+        echo "REPOSITORY="
+        echo "URI=\"https://\${PROVIDER}/\${PROVIDER_USERNAME}/\${REPOSITORY}\""
+        echo "REQUIRED=('git')"
+        echo "COMMANDS=('go:run')"
+        echo "CHANNEL=${i}"
+        echo "TIME=10"
+        echo "INSTALLER=apt-get"
+        echo -e "INSTALL_OPTIONS=install\n"
+        echo "for x in \"\${REQUIRED[@]}\""
+        echo "do"
+        echo -e "\t\${INSTALLER} \${INSTALL_OPTIONS} \"\${x}\""
+        echo -e "done\n"
+        echo "STR=\$(realpath . )"
+        echo "SUB=\"go\""
+        echo -e "\nif [[ \"\$STR\" == *\"\$SUB\"* ]]"
+        echo "then"
+        echo -e "\techo \"\${CHANNEL}\""
+        echo -e "fi\n"
+        echo "git clone \"\${URI}\" continuous && cd continuous || exit 1"
+        echo "git log -1  && sleep \"\${TIME}\" || exit 1"
+        echo -e "\nfor x in \"\${COMMANDS[@]}\""
+        echo "do"
+        echo -e "\tprogram=\$(echo \"\${x}\" | cut -f1 -d :)"
+        echo -e "\targ=\$(echo \"\${x}\" | cut -f2 -d :)"
+        echo -e "\tfilenames=\$(ls ./*.go)"
+        echo -e "\n\tfor f in \${filenames}"
+        echo -e "\tdo"
+        echo -e "\t\t\${program} \"\${arg}\" \"\${f}\""
+        echo -e "\tdone"
+        echo -e "done"
+        echo "cd .."
+        echo "rm -rf continuous"
 
+    } > ${i}
+    chmod +x ${i}
+done
